version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/nonstop/highthon/

hooks:
  AfterInstall:
    - location: sudo chmod +x execute-deploy.sh
      timeout: 180
    - location: ./execute-deploy.sh
      timeout: 180
