spring:
  profiles:
    active: local

limit:
  life-develop: 45
  life-design: 15
  game-develop: 30
  game-design: 10

# 운영환경
---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8001
---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8002

