server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/highthon?useUnicode=true&amp;characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: nooheat
    password: xogns1228
